//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.15 at 11:54:11 AM BDT 
//


package io.naztech.nuxeoclient.model.invoice.ctech;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import io.naztech.nuxeoclient.model.invoice.ctech.InvoiceTable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}_supplierName"/>
 *         &lt;element ref="{}_supplierAddress"/>
 *         &lt;element ref="{}_supplierTelephoneNo"/>
 *         &lt;element ref="{}_email"/>
 *         &lt;element ref="{}_customerName"/>
 *         &lt;element ref="{}_customerAddress"/>
 *         &lt;element ref="{}_invoiceDate"/>
 *         &lt;element ref="{}_referenceNo"/>
 *         &lt;element ref="{}_invoiceTable" maxOccurs="unbounded"/>
 *         &lt;element ref="{}_accountNumber"/>
 *         &lt;element ref="{}_invoiceValueOverdue"/>
 *         &lt;element ref="{}_totalAmountDue"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.abbyy.com/FlexiCapture/Schemas/Export/AdditionalFormData.xsd}ImagePath use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "supplierName",
    "supplierAddress",
    "supplierTelephoneNo",
    "email",
    "customerName",
    "customerAddress",
    "invoiceDate",
    "referenceNo",
    "invoiceTable",
    "accountNumber",
    "invoiceValueOverdue",
    "totalAmountDue"
})
@XmlRootElement(name = "_CTECH_Document_Definition")
public class CTECHDocumentDefinition {

    @XmlElement(name = "_supplierName", required = true)
    protected String supplierName;
    @XmlElement(name = "_supplierAddress", required = true)
    protected String supplierAddress;
    @XmlElement(name = "_supplierTelephoneNo")
    @XmlSchemaType(name = "unsignedInt")
    protected long supplierTelephoneNo;
    @XmlElement(name = "_email", required = true)
    protected String email;
    @XmlElement(name = "_customerName", required = true)
    protected String customerName;
    @XmlElement(name = "_customerAddress", required = true)
    protected String customerAddress;
    @XmlElement(name = "_invoiceDate", required = true)
    protected String invoiceDate;
    @XmlElement(name = "_referenceNo")
    @XmlSchemaType(name = "unsignedByte")
    protected short referenceNo;
    @XmlElement(name = "_invoiceTable", required = true)
    protected List<InvoiceTable> invoiceTable;
    @XmlElement(name = "_accountNumber")
    @XmlSchemaType(name = "unsignedInt")
    protected long accountNumber;
    @XmlElement(name = "_invoiceValueOverdue", required = true)
    protected BigDecimal invoiceValueOverdue;
    @XmlElement(name = "_totalAmountDue", required = true)
    protected String totalAmountDue;
    @XmlAttribute(name = "ImagePath", namespace = "http://www.abbyy.com/FlexiCapture/Schemas/Export/AdditionalFormData.xsd", required = true)
    protected String imagePath;

    /**
     * Gets the value of the supplierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * Sets the value of the supplierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierName(String value) {
        this.supplierName = value;
    }

    /**
     * Gets the value of the supplierAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierAddress() {
        return supplierAddress;
    }

    /**
     * Sets the value of the supplierAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierAddress(String value) {
        this.supplierAddress = value;
    }

    /**
     * Gets the value of the supplierTelephoneNo property.
     * 
     */
    public long getSupplierTelephoneNo() {
        return supplierTelephoneNo;
    }

    /**
     * Sets the value of the supplierTelephoneNo property.
     * 
     */
    public void setSupplierTelephoneNo(long value) {
        this.supplierTelephoneNo = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the customerAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * Sets the value of the customerAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAddress(String value) {
        this.customerAddress = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceDate(String value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the referenceNo property.
     * 
     */
    public short getReferenceNo() {
        return referenceNo;
    }

    /**
     * Sets the value of the referenceNo property.
     * 
     */
    public void setReferenceNo(short value) {
        this.referenceNo = value;
    }

    /**
     * Gets the value of the invoiceTable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceTable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceTable }
     * 
     * 
     */
    public List<InvoiceTable> getInvoiceTable() {
        if (invoiceTable == null) {
            invoiceTable = new ArrayList<InvoiceTable>();
        }
        return this.invoiceTable;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     */
    public long getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     */
    public void setAccountNumber(long value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the invoiceValueOverdue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInvoiceValueOverdue() {
        return invoiceValueOverdue;
    }

    /**
     * Sets the value of the invoiceValueOverdue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInvoiceValueOverdue(BigDecimal value) {
        this.invoiceValueOverdue = value;
    }

    /**
     * Gets the value of the totalAmountDue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalAmountDue() {
        return totalAmountDue;
    }

    /**
     * Sets the value of the totalAmountDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalAmountDue(String value) {
        this.totalAmountDue = value;
    }

    /**
     * Gets the value of the imagePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * Sets the value of the imagePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImagePath(String value) {
        this.imagePath = value;
    }

}
