//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.15 at 11:54:11 AM BDT 
//


package io.naztech.nuxeoclient.model.invoice.ctech;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import io.naztech.nuxeoclient.model.invoice.ctech.CTECHDocumentDefinition;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.abbyy.com/FlexiCapture/Schemas/Export/CTECH_Document_Definition.xsd}_CTECH_Document_Definition"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ctechDocumentDefinition"
})
@XmlRootElement(name = "Documents")
public class Documents {

    @XmlElement(name = "_CTECH_Document_Definition", namespace = "http://www.abbyy.com/FlexiCapture/Schemas/Export/CTECH_Document_Definition.xsd", required = true)
    protected CTECHDocumentDefinition ctechDocumentDefinition;

    /**
     * Gets the value of the ctechDocumentDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link CTECHDocumentDefinition }
     *     
     */
    public CTECHDocumentDefinition getCTECHDocumentDefinition() {
        return ctechDocumentDefinition;
    }

    /**
     * Sets the value of the ctechDocumentDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTECHDocumentDefinition }
     *     
     */
    public void setCTECHDocumentDefinition(CTECHDocumentDefinition value) {
        this.ctechDocumentDefinition = value;
    }

}
