//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.15 at 11:54:11 AM BDT 
//


package io.naztech.nuxeoclient.model.invoice.ctech;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_Invoice" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="_PO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_Due_On" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_Days_Over" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="_Debit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_Credit" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="_Balance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "date",
    "invoice",
    "po",
    "dueOn",
    "daysOver",
    "debit",
    "credit",
    "balance"
})
@XmlRootElement(name = "_invoiceTable")
public class InvoiceTable {

    @XmlElement(name = "_Date", required = true)
    protected String date;
    @XmlElement(name = "_Invoice")
    @XmlSchemaType(name = "unsignedInt")
    protected long invoice;
    @XmlElement(name = "_PO", required = true)
    protected String po;
    @XmlElement(name = "_Due_On", required = true)
    protected String dueOn;
    @XmlElement(name = "_Days_Over", required = true)
    protected Object daysOver;
    @XmlElement(name = "_Debit", required = true)
    protected String debit;
    @XmlElement(name = "_Credit", required = true)
    protected Object credit;
    @XmlElement(name = "_Balance", required = true)
    protected String balance;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the invoice property.
     * 
     */
    public long getInvoice() {
        return invoice;
    }

    /**
     * Sets the value of the invoice property.
     * 
     */
    public void setInvoice(long value) {
        this.invoice = value;
    }

    /**
     * Gets the value of the po property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPO() {
        return po;
    }

    /**
     * Sets the value of the po property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPO(String value) {
        this.po = value;
    }

    /**
     * Gets the value of the dueOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueOn() {
        return dueOn;
    }

    /**
     * Sets the value of the dueOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueOn(String value) {
        this.dueOn = value;
    }

    /**
     * Gets the value of the daysOver property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDaysOver() {
        return daysOver;
    }

    /**
     * Sets the value of the daysOver property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDaysOver(Object value) {
        this.daysOver = value;
    }

    /**
     * Gets the value of the debit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebit() {
        return debit;
    }

    /**
     * Sets the value of the debit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebit(String value) {
        this.debit = value;
    }

    /**
     * Gets the value of the credit property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCredit() {
        return credit;
    }

    /**
     * Sets the value of the credit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCredit(Object value) {
        this.credit = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalance(String value) {
        this.balance = value;
    }

}
