//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 11:28:05 AM BDT 
//


package io.naztech.nuxeoclient.model.invoice.aps;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import io.naztech.nuxeoclient.model.invoice.aps.APSDocumentDefinition;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.abbyy.com/FlexiCapture/Schemas/Export/APS_Document_Definition.xsd}_APS_Document_Definition"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "apsDocumentDefinition"
})
@XmlRootElement(name = "Documents")
public class ApsInvoiceDocument {

    @XmlElement(name = "_APS_Document_Definition", namespace = "http://www.abbyy.com/FlexiCapture/Schemas/Export/APS_Document_Definition.xsd", required = true)
    protected APSDocumentDefinition apsDocumentDefinition;

    /**
     * Gets the value of the apsDocumentDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link APSDocumentDefinition }
     *     
     */
    public APSDocumentDefinition getAPSDocumentDefinition() {
        return apsDocumentDefinition;
    }

    /**
     * Sets the value of the apsDocumentDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link APSDocumentDefinition }
     *     
     */
    public void setAPSDocumentDefinition(APSDocumentDefinition value) {
        this.apsDocumentDefinition = value;
    }

}
