//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 11:28:05 AM BDT 
//


package io.naztech.nuxeoclient.model.invoice.aps;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_Stock_Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_Qty" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="_Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_Unit_Price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="_Disc_Amt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="_Net_Amt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="_VAT_Percentage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="_VAT" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stockCode",
    "qty",
    "description",
    "unitPrice",
    "discAmt",
    "netAmt",
    "vatPercentage",
    "vat"
})
@XmlRootElement(name = "_invoiceTable")
public class InvoiceTable {

    @XmlElement(name = "_Stock_Code", required = true)
    protected String stockCode;
    @XmlElement(name = "_Qty", required = true)
    protected BigDecimal qty;
    @XmlElement(name = "_Description", required = true)
    protected String description;
    @XmlElement(name = "_Unit_Price", required = true)
    protected BigDecimal unitPrice;
    @XmlElement(name = "_Disc_Amt", required = true)
    protected BigDecimal discAmt;
    @XmlElement(name = "_Net_Amt", required = true)
    protected BigDecimal netAmt;
    @XmlElement(name = "_VAT_Percentage", required = true)
    protected BigDecimal vatPercentage;
    @XmlElement(name = "_VAT", required = true)
    protected BigDecimal vat;

    /**
     * Gets the value of the stockCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * Sets the value of the stockCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockCode(String value) {
        this.stockCode = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQty(BigDecimal value) {
        this.qty = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitPrice(BigDecimal value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the discAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscAmt() {
        return discAmt;
    }

    /**
     * Sets the value of the discAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscAmt(BigDecimal value) {
        this.discAmt = value;
    }

    /**
     * Gets the value of the netAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetAmt() {
        return netAmt;
    }

    /**
     * Sets the value of the netAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetAmt(BigDecimal value) {
        this.netAmt = value;
    }

    /**
     * Gets the value of the vatPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVATPercentage() {
        return vatPercentage;
    }

    /**
     * Sets the value of the vatPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVATPercentage(BigDecimal value) {
        this.vatPercentage = value;
    }

    /**
     * Gets the value of the vat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVAT() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVAT(BigDecimal value) {
        this.vat = value;
    }

}
