//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.09 at 03:38:03 PM BDT 
//


package io.naztech.nuxeoclient.model.invoice.ox;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_Qty" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="_Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_RSP" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="_Disc_Persent" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="_Price_Each" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="_Line_Total" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="_VAt_Persent" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="_Line_Vat" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qty",
    "code",
    "description",
    "rsp",
    "discPersent",
    "priceEach",
    "lineTotal",
    "vAtPersent",
    "lineVat"
})
@XmlRootElement(name = "_invoiceTable")
public class InvoiceTable {

    @XmlElement(name = "_Qty")
    @XmlSchemaType(name = "unsignedByte")
    protected short qty;
    @XmlElement(name = "_Code", required = true)
    protected String code;
    @XmlElement(name = "_Description", required = true)
    protected String description;
    @XmlElement(name = "_RSP", required = true)
    protected BigDecimal rsp;
    @XmlElement(name = "_Disc_Persent", required = true)
    protected BigDecimal discPersent;
    @XmlElement(name = "_Price_Each", required = true)
    protected BigDecimal priceEach;
    @XmlElement(name = "_Line_Total", required = true)
    protected BigDecimal lineTotal;
    @XmlElement(name = "_VAt_Persent", required = true)
    protected BigDecimal vAtPersent;
    @XmlElement(name = "_Line_Vat", required = true)
    protected BigDecimal lineVat;

    /**
     * Gets the value of the qty property.
     * 
     */
    public short getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     */
    public void setQty(short value) {
        this.qty = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the rsp property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRSP() {
        return rsp;
    }

    /**
     * Sets the value of the rsp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRSP(BigDecimal value) {
        this.rsp = value;
    }

    /**
     * Gets the value of the discPersent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscPersent() {
        return discPersent;
    }

    /**
     * Sets the value of the discPersent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscPersent(BigDecimal value) {
        this.discPersent = value;
    }

    /**
     * Gets the value of the priceEach property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPriceEach() {
        return priceEach;
    }

    /**
     * Sets the value of the priceEach property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPriceEach(BigDecimal value) {
        this.priceEach = value;
    }

    /**
     * Gets the value of the lineTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineTotal() {
        return lineTotal;
    }

    /**
     * Sets the value of the lineTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineTotal(BigDecimal value) {
        this.lineTotal = value;
    }

    /**
     * Gets the value of the vAtPersent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVAtPersent() {
        return vAtPersent;
    }

    /**
     * Sets the value of the vAtPersent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVAtPersent(BigDecimal value) {
        this.vAtPersent = value;
    }

    /**
     * Gets the value of the lineVat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineVat() {
        return lineVat;
    }

    /**
     * Sets the value of the lineVat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineVat(BigDecimal value) {
        this.lineVat = value;
    }

}
