//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.09 at 03:38:03 PM BDT 
//


package io.naztech.nuxeoclient.model.invoice.ox;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SupplierName_QNAME = new QName("", "_supplierName");
    private final static QName _VatRegNumber_QNAME = new QName("", "_vatRegNumber");
    private final static QName _SupplierTelephoneNo_QNAME = new QName("", "_supplierTelephoneNo");
    private final static QName _SupplierAddress_QNAME = new QName("", "_supplierAddress");
    private final static QName _Email_QNAME = new QName("", "_email");
    private final static QName _Vat_QNAME = new QName("", "_vat");
    private final static QName _FaxNumber_QNAME = new QName("", "_faxNumber");
    private final static QName _InvoiceNumber_QNAME = new QName("", "_invoiceNumber");
    private final static QName _OrderNo_QNAME = new QName("", "_orderNo");
    private final static QName _CustomerName_QNAME = new QName("", "_customerName");
    private final static QName _CustomerAddress_QNAME = new QName("", "_customerAddress");
    private final static QName _DeliveryNumber_QNAME = new QName("", "_deliveryNumber");
    private final static QName _ValueOfGoods_QNAME = new QName("", "_valueOfGoods");
    private final static QName _OrderId_QNAME = new QName("", "_orderId");
    private final static QName _DeliveryAddress_QNAME = new QName("", "_deliveryAddress");
    private final static QName _ReferenceNo_QNAME = new QName("", "_referenceNo");
    private final static QName _NetInvoiceTotal_QNAME = new QName("", "_netInvoiceTotal");
    private final static QName _SupplierAccountNumber_QNAME = new QName("", "_supplierAccountNumber");
    private final static QName _InvoiceDate_QNAME = new QName("", "_invoiceDate");
    private final static QName _OrderDate_QNAME = new QName("", "_orderDate");
    private final static QName _AccountNumber_QNAME = new QName("", "_accountNumber");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceTable }
     * 
     */
    public InvoiceTable createInvoiceTable() {
        return new InvoiceTable();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_supplierName")
    public JAXBElement<String> createSupplierName(String value) {
        return new JAXBElement<String>(_SupplierName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_vatRegNumber")
    public JAXBElement<String> createVatRegNumber(String value) {
        return new JAXBElement<String>(_VatRegNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_supplierTelephoneNo")
    public JAXBElement<Object> createSupplierTelephoneNo(Object value) {
        return new JAXBElement<Object>(_SupplierTelephoneNo_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_supplierAddress")
    public JAXBElement<String> createSupplierAddress(String value) {
        return new JAXBElement<String>(_SupplierAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_email")
    public JAXBElement<Object> createEmail(Object value) {
        return new JAXBElement<Object>(_Email_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_vat")
    public JAXBElement<BigDecimal> createVat(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Vat_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_faxNumber")
    public JAXBElement<Object> createFaxNumber(Object value) {
        return new JAXBElement<Object>(_FaxNumber_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_invoiceNumber")
    public JAXBElement<Long> createInvoiceNumber(Long value) {
        return new JAXBElement<Long>(_InvoiceNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_orderNo")
    public JAXBElement<Long> createOrderNo(Long value) {
        return new JAXBElement<Long>(_OrderNo_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_customerName")
    public JAXBElement<String> createCustomerName(String value) {
        return new JAXBElement<String>(_CustomerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_customerAddress")
    public JAXBElement<String> createCustomerAddress(String value) {
        return new JAXBElement<String>(_CustomerAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_deliveryNumber")
    public JAXBElement<Long> createDeliveryNumber(Long value) {
        return new JAXBElement<Long>(_DeliveryNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_valueOfGoods")
    public JAXBElement<BigDecimal> createValueOfGoods(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ValueOfGoods_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_orderId")
    public JAXBElement<String> createOrderId(String value) {
        return new JAXBElement<String>(_OrderId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_deliveryAddress")
    public JAXBElement<String> createDeliveryAddress(String value) {
        return new JAXBElement<String>(_DeliveryAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_referenceNo")
    public JAXBElement<String> createReferenceNo(String value) {
        return new JAXBElement<String>(_ReferenceNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_netInvoiceTotal")
    public JAXBElement<BigDecimal> createNetInvoiceTotal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NetInvoiceTotal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_supplierAccountNumber")
    public JAXBElement<String> createSupplierAccountNumber(String value) {
        return new JAXBElement<String>(_SupplierAccountNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_invoiceDate")
    public JAXBElement<String> createInvoiceDate(String value) {
        return new JAXBElement<String>(_InvoiceDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_orderDate")
    public JAXBElement<String> createOrderDate(String value) {
        return new JAXBElement<String>(_OrderDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_accountNumber")
    public JAXBElement<Long> createAccountNumber(Long value) {
        return new JAXBElement<Long>(_AccountNumber_QNAME, Long.class, null, value);
    }

}
