//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.02 at 05:07:00 PM BDT 
//


package io.naztech.nuxeoclient.model.invoice.bristanGroup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import io.naztech.nuxeoclient.model.invoice.bristanGroup.BristanGroupDocumentDefinition;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.abbyy.com/FlexiCapture/Schemas/Export/BristanGroup_Document_Definition.xsd}_BristanGroup_Document_Definition"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bristanGroupDocumentDefinition"
})
@XmlRootElement(name = "Documents")
public class BristanGroupInvoiceDocuments {

    @XmlElement(name = "_BristanGroup_Document_Definition", namespace = "http://www.abbyy.com/FlexiCapture/Schemas/Export/BristanGroup_Document_Definition.xsd", required = true)
    protected BristanGroupDocumentDefinition bristanGroupDocumentDefinition;

    /**
     * Gets the value of the bristanGroupDocumentDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link BristanGroupDocumentDefinition }
     *     
     */
    public BristanGroupDocumentDefinition getBristanGroupDocumentDefinition() {
        return bristanGroupDocumentDefinition;
    }

    /**
     * Sets the value of the bristanGroupDocumentDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BristanGroupDocumentDefinition }
     *     
     */
    public void setBristanGroupDocumentDefinition(BristanGroupDocumentDefinition value) {
        this.bristanGroupDocumentDefinition = value;
    }

}
