//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.02 at 05:07:00 PM BDT 
//


package io.naztech.nuxeoclient.model.invoice.bristanGroup;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import io.naztech.nuxeoclient.model.invoice.bristanGroup.InvoiceTable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}_customerName"/>
 *         &lt;element ref="{}_deliveryAddress"/>
 *         &lt;element ref="{}_refNumber"/>
 *         &lt;element ref="{}_supplierAccountNumber"/>
 *         &lt;element ref="{}_orderNo"/>
 *         &lt;element ref="{}_invoiceDate"/>
 *         &lt;element ref="{}_valueOfGoods"/>
 *         &lt;element ref="{}_vat"/>
 *         &lt;element ref="{}_netInvoiceTotal"/>
 *         &lt;element ref="{}_invoiceNumber"/>
 *         &lt;element ref="{}_customerAddress"/>
 *         &lt;element ref="{}_invoiceTable" maxOccurs="unbounded"/>
 *         &lt;element ref="{}_supplierName"/>
 *         &lt;element ref="{}_supplierAddress"/>
 *         &lt;element ref="{}_supplierTelephoneNo"/>
 *         &lt;element ref="{}_faxNumber"/>
 *         &lt;element ref="{}_vatRegNumber"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.abbyy.com/FlexiCapture/Schemas/Export/AdditionalFormData.xsd}ImagePath use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerName",
    "deliveryAddress",
    "refNumber",
    "supplierAccountNumber",
    "orderNo",
    "invoiceDate",
    "valueOfGoods",
    "vat",
    "netInvoiceTotal",
    "invoiceNumber",
    "customerAddress",
    "invoiceTable",
    "supplierName",
    "supplierAddress",
    "supplierTelephoneNo",
    "faxNumber",
    "vatRegNumber"
})
@XmlRootElement(name = "_BristanGroup_Document_Definition")
public class BristanGroupDocumentDefinition {

    @XmlElement(name = "_customerName", required = true)
    protected String customerName;
    @XmlElement(name = "_deliveryAddress", required = true)
    protected String deliveryAddress;
    @XmlElement(name = "_refNumber", required = true)
    protected String refNumber;
    @XmlElement(name = "_supplierAccountNumber", required = true)
    protected String supplierAccountNumber;
    @XmlElement(name = "_orderNo", required = true)
    protected String orderNo;
    @XmlElement(name = "_invoiceDate", required = true)
    protected String invoiceDate;
    @XmlElement(name = "_valueOfGoods", required = true)
    protected String valueOfGoods;
    @XmlElement(name = "_vat", required = true)
    protected String vat;
    @XmlElement(name = "_netInvoiceTotal", required = true)
    protected String netInvoiceTotal;
    @XmlElement(name = "_invoiceNumber", required = true)
    protected String invoiceNumber;
    @XmlElement(name = "_customerAddress", required = true)
    protected String customerAddress;
    @XmlElement(name = "_invoiceTable", required = true)
    protected List<InvoiceTable> invoiceTable;
    @XmlElement(name = "_supplierName", required = true)
    protected String supplierName;
    @XmlElement(name = "_supplierAddress", required = true)
    protected String supplierAddress;
    @XmlElement(name = "_supplierTelephoneNo")
    @XmlSchemaType(name = "unsignedInt")
    protected long supplierTelephoneNo;
    @XmlElement(name = "_faxNumber", required = true)
    protected String faxNumber;
    @XmlElement(name = "_vatRegNumber", required = true)
    protected String vatRegNumber;
    @XmlAttribute(name = "ImagePath", namespace = "http://www.abbyy.com/FlexiCapture/Schemas/Export/AdditionalFormData.xsd", required = true)
    protected String imagePath;

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the deliveryAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    /**
     * Sets the value of the deliveryAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryAddress(String value) {
        this.deliveryAddress = value;
    }

    /**
     * Gets the value of the refNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefNumber() {
        return refNumber;
    }

    /**
     * Sets the value of the refNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefNumber(String value) {
        this.refNumber = value;
    }

    /**
     * Gets the value of the supplierAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierAccountNumber() {
        return supplierAccountNumber;
    }

    /**
     * Sets the value of the supplierAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierAccountNumber(String value) {
        this.supplierAccountNumber = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNo(String value) {
        this.orderNo = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceDate(String value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the valueOfGoods property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueOfGoods() {
        return valueOfGoods;
    }

    /**
     * Sets the value of the valueOfGoods property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueOfGoods(String value) {
        this.valueOfGoods = value;
    }

    /**
     * Gets the value of the vat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVat() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVat(String value) {
        this.vat = value;
    }

    /**
     * Gets the value of the netInvoiceTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetInvoiceTotal() {
        return netInvoiceTotal;
    }

    /**
     * Sets the value of the netInvoiceTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetInvoiceTotal(String value) {
        this.netInvoiceTotal = value;
    }

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the customerAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * Sets the value of the customerAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAddress(String value) {
        this.customerAddress = value;
    }

    /**
     * Gets the value of the invoiceTable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceTable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceTable }
     * 
     * 
     */
    public List<InvoiceTable> getInvoiceTable() {
        if (invoiceTable == null) {
            invoiceTable = new ArrayList<InvoiceTable>();
        }
        return this.invoiceTable;
    }

    /**
     * Gets the value of the supplierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * Sets the value of the supplierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierName(String value) {
        this.supplierName = value;
    }

    /**
     * Gets the value of the supplierAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierAddress() {
        return supplierAddress;
    }

    /**
     * Sets the value of the supplierAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierAddress(String value) {
        this.supplierAddress = value;
    }

    /**
     * Gets the value of the supplierTelephoneNo property.
     * 
     */
    public long getSupplierTelephoneNo() {
        return supplierTelephoneNo;
    }

    /**
     * Sets the value of the supplierTelephoneNo property.
     * 
     */
    public void setSupplierTelephoneNo(long value) {
        this.supplierTelephoneNo = value;
    }

    /**
     * Gets the value of the faxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxNumber() {
        return faxNumber;
    }

    /**
     * Sets the value of the faxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxNumber(String value) {
        this.faxNumber = value;
    }

    /**
     * Gets the value of the vatRegNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatRegNumber() {
        return vatRegNumber;
    }

    /**
     * Sets the value of the vatRegNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatRegNumber(String value) {
        this.vatRegNumber = value;
    }

    /**
     * Gets the value of the imagePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * Sets the value of the imagePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImagePath(String value) {
        this.imagePath = value;
    }

}
