//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.02 at 05:07:00 PM BDT 
//


package io.naztech.nuxeoclient.model.invoice.bristanGroup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_Part_Number_Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_Quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_Unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_Trade_Price" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_Discount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_VAT_Present" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "partNumberDescription",
    "quantity",
    "unit",
    "tradePrice",
    "discount",
    "value",
    "vatPresent"
})
@XmlRootElement(name = "_invoiceTable")
public class InvoiceTable {

    @XmlElement(name = "_Part_Number_Description", required = true)
    protected String partNumberDescription;
    @XmlElement(name = "_Quantity", required = true)
    protected String quantity;
    @XmlElement(name = "_Unit", required = true)
    protected String unit;
    @XmlElement(name = "_Trade_Price", required = true)
    protected String tradePrice;
    @XmlElement(name = "_Discount", required = true)
    protected String discount;
    @XmlElement(name = "_Value", required = true)
    protected String value;
    @XmlElement(name = "_VAT_Present", required = true)
    protected String vatPresent;

    /**
     * Gets the value of the partNumberDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartNumberDescription() {
        return partNumberDescription;
    }

    /**
     * Sets the value of the partNumberDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartNumberDescription(String value) {
        this.partNumberDescription = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantity(String value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the tradePrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradePrice() {
        return tradePrice;
    }

    /**
     * Sets the value of the tradePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradePrice(String value) {
        this.tradePrice = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscount(String value) {
        this.discount = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the vatPresent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVATPresent() {
        return vatPresent;
    }

    /**
     * Sets the value of the vatPresent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVATPresent(String value) {
        this.vatPresent = value;
    }

}
