//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.09 at 02:58:53 PM BDT 
//


package io.naztech.nuxeoclient.model.invoice.nmbs;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_V" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_PRODUCT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_QTY_WEIGHT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_PRICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_DISCOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "v",
    "productcode",
    "description",
    "qtyweight",
    "price",
    "discount",
    "amount"
})
@XmlRootElement(name = "_invoiceTable")
public class InvoiceTable {

    @XmlElement(name = "_V", required = true)
    protected String v;
    @XmlElement(name = "_PRODUCT_CODE", required = true)
    protected String productcode;
    @XmlElement(name = "_DESCRIPTION", required = true)
    protected String description;
    @XmlElement(name = "_QTY_WEIGHT", required = true)
    protected String qtyweight;
    @XmlElement(name = "_PRICE", required = true)
    protected String price;
    @XmlElement(name = "_DISCOUNT", required = true)
    protected BigDecimal discount;
    @XmlElement(name = "_AMOUNT", required = true)
    protected BigDecimal amount;

    /**
     * Gets the value of the v property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getV() {
        return v;
    }

    /**
     * Sets the value of the v property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setV(String value) {
        this.v = value;
    }

    /**
     * Gets the value of the productcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTCODE() {
        return productcode;
    }

    /**
     * Sets the value of the productcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTCODE(String value) {
        this.productcode = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the qtyweight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQTYWEIGHT() {
        return qtyweight;
    }

    /**
     * Sets the value of the qtyweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQTYWEIGHT(String value) {
        this.qtyweight = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRICE() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRICE(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDISCOUNT() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDISCOUNT(BigDecimal value) {
        this.discount = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAMOUNT() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAMOUNT(BigDecimal value) {
        this.amount = value;
    }

}
