//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.09 at 02:58:53 PM BDT 
//


package io.naztech.nuxeoclient.model.invoice.nmbs;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import io.naztech.nuxeoclient.model.invoice.nmbs.InvoiceTable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}_invoiceNumber"/>
 *         &lt;element ref="{}_voucherNumber"/>
 *         &lt;element ref="{}_faxNumber"/>
 *         &lt;element ref="{}_invoiceDate"/>
 *         &lt;element ref="{}_orderNumber"/>
 *         &lt;element ref="{}_accountNumber"/>
 *         &lt;element ref="{}_deliveryNote"/>
 *         &lt;element ref="{}_itemCode"/>
 *         &lt;element ref="{}_valueOfGoods"/>
 *         &lt;element ref="{}_vat"/>
 *         &lt;element ref="{}_netInvoiceTotal"/>
 *         &lt;element ref="{}_invoiceTable"/>
 *         &lt;element ref="{}_customerName"/>
 *         &lt;element ref="{}_deliveryAddress"/>
 *         &lt;element ref="{}_companyName"/>
 *         &lt;element ref="{}_companyAddress"/>
 *         &lt;element ref="{}_companyTelephoneNo"/>
 *         &lt;element ref="{}_vatRegNumber"/>
 *         &lt;element ref="{}_customerAddress"/>
 *         &lt;element ref="{}_supplierName"/>
 *         &lt;element ref="{}_supplierAddress"/>
 *         &lt;element ref="{}_supplierTelephoneNo"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.abbyy.com/FlexiCapture/Schemas/Export/AdditionalFormData.xsd}ImagePath use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoiceNumber",
    "voucherNumber",
    "faxNumber",
    "invoiceDate",
    "orderNumber",
    "accountNumber",
    "deliveryNote",
    "itemCode",
    "valueOfGoods",
    "vat",
    "netInvoiceTotal",
    "invoiceTable",
    "customerName",
    "deliveryAddress",
    "companyName",
    "companyAddress",
    "companyTelephoneNo",
    "vatRegNumber",
    "customerAddress",
    "supplierName",
    "supplierAddress",
    "supplierTelephoneNo"
})
@XmlRootElement(name = "_Nmbs_Document_Definition")
public class NmbsDocumentDefinition {

    @XmlElement(name = "_invoiceNumber")
    @XmlSchemaType(name = "unsignedInt")
    protected long invoiceNumber;
    @XmlElement(name = "_voucherNumber", required = true)
    protected String voucherNumber;
    @XmlElement(name = "_faxNumber", required = true)
    protected String faxNumber;
    @XmlElement(name = "_invoiceDate", required = true)
    protected String invoiceDate;
    @XmlElement(name = "_orderNumber", required = true)
    protected String orderNumber;
    @XmlElement(name = "_accountNumber", required = true)
    protected String accountNumber;
    @XmlElement(name = "_deliveryNote")
    @XmlSchemaType(name = "unsignedInt")
    protected long deliveryNote;
    @XmlElement(name = "_itemCode", required = true)
    protected String itemCode;
    @XmlElement(name = "_valueOfGoods", required = true)
    protected BigDecimal valueOfGoods;
    @XmlElement(name = "_vat", required = true)
    protected BigDecimal vat;
    @XmlElement(name = "_netInvoiceTotal", required = true)
    protected BigDecimal netInvoiceTotal;
    @XmlElement(name = "_invoiceTable", required = true)
    protected ArrayList<InvoiceTable> invoiceTable;
    @XmlElement(name = "_customerName", required = true)
    protected String customerName;
    @XmlElement(name = "_deliveryAddress", required = true)
    protected String deliveryAddress;
    @XmlElement(name = "_companyName", required = true)
    protected String companyName;
    @XmlElement(name = "_companyAddress", required = true)
    protected String companyAddress;
    @XmlElement(name = "_companyTelephoneNo", required = true)
    protected String companyTelephoneNo;
    @XmlElement(name = "_vatRegNumber")
    @XmlSchemaType(name = "unsignedInt")
    protected long vatRegNumber;
    @XmlElement(name = "_customerAddress", required = true)
    protected String customerAddress;
    @XmlElement(name = "_supplierName", required = true)
    protected Object supplierName;
    @XmlElement(name = "_supplierAddress", required = true)
    protected Object supplierAddress;
    @XmlElement(name = "_supplierTelephoneNo", required = true)
    protected Object supplierTelephoneNo;
    @XmlAttribute(name = "ImagePath", namespace = "http://www.abbyy.com/FlexiCapture/Schemas/Export/AdditionalFormData.xsd", required = true)
    protected String imagePath;

    /**
     * Gets the value of the invoiceNumber property.
     * 
     */
    public long getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     */
    public void setInvoiceNumber(long value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the voucherNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherNumber() {
        return voucherNumber;
    }

    /**
     * Sets the value of the voucherNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherNumber(String value) {
        this.voucherNumber = value;
    }

    /**
     * Gets the value of the faxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxNumber() {
        return faxNumber;
    }

    /**
     * Sets the value of the faxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxNumber(String value) {
        this.faxNumber = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceDate(String value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the orderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * Sets the value of the orderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNumber(String value) {
        this.orderNumber = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the deliveryNote property.
     * 
     */
    public long getDeliveryNote() {
        return deliveryNote;
    }

    /**
     * Sets the value of the deliveryNote property.
     * 
     */
    public void setDeliveryNote(long value) {
        this.deliveryNote = value;
    }

    /**
     * Gets the value of the itemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * Sets the value of the itemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemCode(String value) {
        this.itemCode = value;
    }

    /**
     * Gets the value of the valueOfGoods property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValueOfGoods() {
        return valueOfGoods;
    }

    /**
     * Sets the value of the valueOfGoods property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValueOfGoods(BigDecimal value) {
        this.valueOfGoods = value;
    }

    /**
     * Gets the value of the vat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVat() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVat(BigDecimal value) {
        this.vat = value;
    }

    /**
     * Gets the value of the netInvoiceTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetInvoiceTotal() {
        return netInvoiceTotal;
    }

    /**
     * Sets the value of the netInvoiceTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetInvoiceTotal(BigDecimal value) {
        this.netInvoiceTotal = value;
    }

    /**
     * Gets the value of the invoiceTable property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceTable }
     *     
     */
    public List<InvoiceTable> getInvoiceTable() {
        if (invoiceTable == null) {
            invoiceTable = new ArrayList<InvoiceTable>();
        }
        return this.invoiceTable;
    }

    /**
     * Sets the value of the invoiceTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceTable }
     *     
     */
    public void setInvoiceTable(ArrayList<InvoiceTable> value) {
        this.invoiceTable = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the deliveryAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    /**
     * Sets the value of the deliveryAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryAddress(String value) {
        this.deliveryAddress = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the companyAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * Sets the value of the companyAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyAddress(String value) {
        this.companyAddress = value;
    }

    /**
     * Gets the value of the companyTelephoneNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyTelephoneNo() {
        return companyTelephoneNo;
    }

    /**
     * Sets the value of the companyTelephoneNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyTelephoneNo(String value) {
        this.companyTelephoneNo = value;
    }

    /**
     * Gets the value of the vatRegNumber property.
     * 
     */
    public long getVatRegNumber() {
        return vatRegNumber;
    }

    /**
     * Sets the value of the vatRegNumber property.
     * 
     */
    public void setVatRegNumber(long value) {
        this.vatRegNumber = value;
    }

    /**
     * Gets the value of the customerAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * Sets the value of the customerAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAddress(String value) {
        this.customerAddress = value;
    }

    /**
     * Gets the value of the supplierName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSupplierName() {
        return supplierName;
    }

    /**
     * Sets the value of the supplierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSupplierName(Object value) {
        this.supplierName = value;
    }

    /**
     * Gets the value of the supplierAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSupplierAddress() {
        return supplierAddress;
    }

    /**
     * Sets the value of the supplierAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSupplierAddress(Object value) {
        this.supplierAddress = value;
    }

    /**
     * Gets the value of the supplierTelephoneNo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSupplierTelephoneNo() {
        return supplierTelephoneNo;
    }

    /**
     * Sets the value of the supplierTelephoneNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSupplierTelephoneNo(Object value) {
        this.supplierTelephoneNo = value;
    }

    /**
     * Gets the value of the imagePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * Sets the value of the imagePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImagePath(String value) {
        this.imagePath = value;
    }

}
