//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.29 at 05:23:53 PM BDT 
//


package io.naztech.nuxeoclient.model.invoice.festool;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SupplierName_QNAME = new QName("", "_supplierName");
    private final static QName _Currency_QNAME = new QName("", "_currency");
    private final static QName _VatRegNumber_QNAME = new QName("", "_vatRegNumber");
    private final static QName _SupplierAddress_QNAME = new QName("", "_supplierAddress");
    private final static QName _SupplierTelephoneNo_QNAME = new QName("", "_supplierTelephoneNo");
    private final static QName _Vat_QNAME = new QName("", "_vat");
    private final static QName _FaxNumber_QNAME = new QName("", "_faxNumber");
    private final static QName _OrderNo_QNAME = new QName("", "_orderNo");
    private final static QName _DocumentNumber_QNAME = new QName("", "_documentNumber");
    private final static QName _CustomerName_QNAME = new QName("", "_customerName");
    private final static QName _CustomerAddress_QNAME = new QName("", "_customerAddress");
    private final static QName _CustomerNumber_QNAME = new QName("", "_customerNumber");
    private final static QName _ValueOfGoods_QNAME = new QName("", "_valueOfGoods");
    private final static QName _DeliveryNoteNo_QNAME = new QName("", "_deliveryNoteNo");
    private final static QName _ReferenceNo_QNAME = new QName("", "_referenceNo");
    private final static QName _NetInvoiceTotal_QNAME = new QName("", "_netInvoiceTotal");
    private final static QName _InvoiceDate_QNAME = new QName("", "_invoiceDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceTable }
     * 
     */
    public InvoiceTable createInvoiceTable() {
        return new InvoiceTable();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_supplierName")
    public JAXBElement<String> createSupplierName(String value) {
        return new JAXBElement<String>(_SupplierName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_currency")
    public JAXBElement<String> createCurrency(String value) {
        return new JAXBElement<String>(_Currency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_vatRegNumber")
    public JAXBElement<String> createVatRegNumber(String value) {
        return new JAXBElement<String>(_VatRegNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_supplierAddress")
    public JAXBElement<String> createSupplierAddress(String value) {
        return new JAXBElement<String>(_SupplierAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_supplierTelephoneNo")
    public JAXBElement<String> createSupplierTelephoneNo(String value) {
        return new JAXBElement<String>(_SupplierTelephoneNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_vat")
    public JAXBElement<BigDecimal> createVat(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Vat_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_faxNumber")
    public JAXBElement<String> createFaxNumber(String value) {
        return new JAXBElement<String>(_FaxNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_orderNo")
    public JAXBElement<Long> createOrderNo(Long value) {
        return new JAXBElement<Long>(_OrderNo_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_documentNumber")
    public JAXBElement<Long> createDocumentNumber(Long value) {
        return new JAXBElement<Long>(_DocumentNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_customerName")
    public JAXBElement<String> createCustomerName(String value) {
        return new JAXBElement<String>(_CustomerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_customerAddress")
    public JAXBElement<String> createCustomerAddress(String value) {
        return new JAXBElement<String>(_CustomerAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_customerNumber")
    public JAXBElement<Long> createCustomerNumber(Long value) {
        return new JAXBElement<Long>(_CustomerNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_valueOfGoods")
    public JAXBElement<BigDecimal> createValueOfGoods(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ValueOfGoods_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_deliveryNoteNo")
    public JAXBElement<Long> createDeliveryNoteNo(Long value) {
        return new JAXBElement<Long>(_DeliveryNoteNo_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_referenceNo")
    public JAXBElement<Object> createReferenceNo(Object value) {
        return new JAXBElement<Object>(_ReferenceNo_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_netInvoiceTotal")
    public JAXBElement<BigDecimal> createNetInvoiceTotal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NetInvoiceTotal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "_invoiceDate")
    public JAXBElement<String> createInvoiceDate(String value) {
        return new JAXBElement<String>(_InvoiceDate_QNAME, String.class, null, value);
    }

}
